#!/usr/bin/env bash
##? usage : compare_folder [folder] [folder]
##? help  : Print difference between 2 folders.

source "$DOTFILES_PATH/scripts/_main.sh"

folder1="$(realpath "$1")"
folder2="$(realpath "$2")"

diffs=$(diff -rq "$folder1" "$folder2")

if [ -n "$diffs" ]; then
  _warning "Difference found:"
  echo "$diffs"
else
  _error "Folders are equales."
fi
