#!/usr/bin/env bash
##? usage : create_playlist [folder]
##? help  : create a playlist with mp3 and mp4 files in folder.

if [ $# -eq 0 ]; then
	folder="$(pwd | awk -F '/' '{print $NF}')"
	path="$(pwd)"
else
	folder="$1"
	path="$(realpath "$folder")"
	if [ $folder == "." ]; then
		folder=$(basename "$path")
	fi
fi

name="playlist_$folder.m3u"
echo -e "#!/usr/bin/vlc\n# $(date)\n# $path\n" >$name
fd -t f --regex "mp\d$" -d1 "$path" | sort >> $name
