#!/usr/bin/env sh
##? Help : create a playlist with mp3 and mp4 files in folder.
##? Usage: create_playlist <folder>

if [ $1 ]; then
	folder=$1
	root="$(pwd)/$1"
else
	folder="$(pwd | awk -F '/' '{print $NF}')"
	root="$(pwd)"
fi
name="playlist_$folder.m3u"
echo -e "#!/usr/bin/vlc\n# $(date)\n# $root\n" >$name
fd "mp\d$" -a -d1 --base-directory $root >>$name
