#!/usr/bin/env bash
##? usage : extract [file]
##? help  : Extract a compressed file.

source "$DOTFILES_PATH/scripts/_main.sh"

file=$1
case $file in
*.7z) 7z x $file ;;
*.gz) gunzip $file ;;
*.bz2) bunzip2 $file ;;
*.zip) unzip $file ;;
*.tar) tar $file ;;
*) _error "Not compressed file" ;;
esac
