#!/usr/bin/env sh
# ? description: Print mimetypes.
# ? usage      : mimetype [file(s)|directory(s)]

. "$HOME/.bin/_main.sh"

if [ $# -lt 1 ]; then
	_params_required 1
	exit 1
fi

for element in "$@"; do
	file --mime-type "$element"
done
