#!/usr/bin/env sh
# ? description: Print mimetypes.
# ? usage      : mimetype [file(s)|directory(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for element in "$@"; do
	file --mime-type "$element"
done
