#!/usr/bin/env bash
##? help  : Print mimetypes.
##? usage : mimetype [element]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

for element in "$@"; do
	file --mime-type "$element"
done
