#!/usr/bin/env python
##? help  : Move files to folder by MIME.
##? usage : refactor_files [folder|empty]

from subprocess import check_output
from shutil import move
from sys import argv, exit
from os import listdir, path, getcwd

home = path.expanduser("~")
xdg_user_dir = lambda type: check_output( ["xdg-user-dir", type.upper()], universal_newlines=True ).strip()


mimeTypes = {
    xdg_user_dir("MUSIC"): ["audio"],
    xdg_user_dir("USERFONTS"): ["font"],
    xdg_user_dir("PICTURES"): ["image", "gbr"],
    xdg_user_dir("VIDEOS"): ["video"],
    xdg_user_dir("DOCUMENTS"): ["pdf", "opendocument", "zip", "epub"],
    xdg_user_dir("TEMPLATES"): ["template", "desktop"],
    f"{home}/Virtual Machines": [ "octet-stream", "x-qemu-disk", "vdi", "ovf", "ova", "iso", ],
    f"{home}/.ssh": ["x-pem-file", "x-ssh-public-key"],
}


def mv(file):
    get_mime_type = lambda file: check_output(["file", "--mime-type", "-b", file], text=True).strip()
    try:
        mime = get_mime_type(file)
        extension = path.splitext(file)[1][1:]
        for folder, types in mimeTypes.items():
            if any(t in mime for t in types) or extension in types:
                move(file, folder)
                print(f"[*] {file.split('/')[-1]} -> {folder}")
    except Exception as e:
        print(f"[ERROR] {file} :: {e}")


def refactor_files(ruta):
    try:
        for archivo in listdir(ruta):
            ruta_completa = path.join(ruta, f"{archivo}")
            if path.isfile(ruta_completa):
                mv(ruta_completa)
    except OSError as e:
        print(f"Error al acceder al directorio {ruta}: {e}")


def main():
    directorio = getcwd()

    if len(argv) > 2: exit(1)
    if len(argv) == 2 and argv[1] != ".": folder = argv[1]
    else: folder = path.abspath(directorio)

    directorio = path.join(directorio, folder)
    refactor_files(directorio)


main()
