#!/usr/bin/env sh
# ? description: Transform file-name to all disk format.
# ? usage      : prettier_name [file(s)|directory(s)]

for f in "$@"; do
    file=$(basename "$f")
    name="${file%.*}"
    extension="${file##*.}"
    name="${name,,^}" # Capitalize first letter
    name=$(echo "$name" | sed 's/[<>:"/\\|?*_]/ /g')
    name=$(echo "$name" | tr -s ' ')
    name=$(echo "$name" | sed 's/^ *//;s/ *$//')
    name=$(echo "$name" | sed 's/^_//;s/_$//')
    mv -v $file "$name.$extension"
done
