#!/usr/bin/env sh
##? usage : refactor_files [folder|empty]
##? help  : Move files to folder by MIME.

if [ $# -eq 0 ]; then
	folder="$(pwd | awk -F '/' '{print $NF}')"
	path="$(realpath .)"
else
	path="$(realpath $1)"
fi

for file in $path/*; do
	mimetype=$(file -b --mime-type "$file")
	mime=$(echo $mimetype | cut -d '/' -f1)
	type=$(echo $mimetype | cut -d '/' -f2)
	case $mime in
	audio) mv -v "$file" "$(xdg-user-dir MUSIC)/" ;;
	font) mv "$file" "$(xdg-user-dir USERFONTS)" ;;
	image) mv -v "$file" "$(xdg-user-dir PICTURES)/" ;;
	video) mv -v "$file" "$(xdg-user-dir VIDEOS)/" ;;
	esac

	case $type in
	pdf | *opendocument*) mv -v "$file" "$(xdg-user-dir DOCUMENTS)/" ;;
	*template) mv -v "$file" "$(xdg-user-dir TEMPLATES)/" ;;
	*rom | octet-stream) mv -v "$file" "$HOME/Games/" ;;
	esac
done
