#!/usr/bin/env bash
##? usage : rename_by_date [folder]
##? help  : Rename all files in folder with the name "folder_id".ext, the `id` is a number ordered by date creation

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

folder="$1"

if [ $folder == "." ]; then
	folder=$(realpath .)
elif [ ! -d "$folder" ]; then
	_error "$folder not exist."
	exit 1
else
	cd "$folder"
fi

files=($(ls -t -1))
cont=1

for file in "${files[@]}"; do
	extension="${file##*.}"
	nuevo_nombre="${folder}_${cont}"
	if [ -n "$extension" ]; then
		nuevo_nombre="$nuevo_nombre.$extension"
	fi

	mv "$file" "$nuevo_nombre"
	_success "Renombrado: $file -> $nuevo_nombre"
	cont=$((cont + 1))
done
