#!/usr/bin/env bash
##? help  : Open/Exec a file in the default editor.
##? usage : run [file]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

file=$1
extension=$(basename "$file" | awk -F . '{print $NF}')
case $file in
*.sh | *.zsh | *.bash) $extension $file ;;
*.py) python $file ;;
*.java) javac $file ;;
*.c | *.h) gcc $file ;;
*.cpp | *.hpp) g++ $file ;;
*.js | *.ts) deno run $file ;;
*.html | *.htm | *.xhtm) xdg-open $file ;;
*.php) php -f $file ;;
*.mp3 | *.mp4 | *.m4a | *.aac | *.flac) xdg-open $file ;;
*.pdf) xdg-open $file ;;
*.jpg | *.jpeg | *.png | *.gif | *.bmp | *.tiff | *.svg) feh $file ;;
*.cs) dotnet run;;
*.cs-proj) dotnet run --project $file;;
*) xdg-open $file ;;
esac
