#!/usr/bin/env bash
##? usage : visibility [file|folder]
##? help  : Change the visibility of a file.

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

if [ ${1:0:1} = "." ]; then
	file=${1:1}
else
	file=".$1"
fi
mv $1 $file
