#!/usr/bin/env sh
# ? description: Encrypt img disk with luks.
# ? usage      : encrypt_disk [.img]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

DEVICE="$1"

_warning "Se va a formatear con LUKS: $DEVICE"
read -rp "¿Estás seguro? (yes para continuar): " confirm

if [ "$confirm" = "yes" ]; then
    sudo cryptsetup luksFormat "$DEVICE"
    _success "Dispositivo $DEVICE formateado con LUKS."
else
    _error "Operación cancelada."
fi
