#!/usr/bin/env sh
#?help : Mount the partition with LABEL on the media folder.
#?usage: mount_disk [name]

. "$HOME/.bin/_main.sh"

if [ $# -lt 1 ]; then
	_params_required 1
	exit 1
fi

label=$(lsblk -o LABEL | grep "$1")
device=$(blkid -l -o device -t LABEL="$label")
d="/run/media/$USER/$label"
sudo mkdir -p "$d" && sudo mount "$device" "$d"
_success "Montado: $device -> $d"
