#!/usr/bin/env sh
# ? description: pastes the content of the clipboard into a specified file or creates a new file in a specified directory.
# ? usage      : clipboard_to_file [file|directory]

. "$HOME/.bin/_main.sh"

clip=$(xclip -o -selection clipboard)

if [ -z "$clip" ]; then
    _error "El portapapeles no contiene texto."
    exit 1
fi

if [ $# -lt 1 ]; then
    # Si no recibe parámetros, pedir el nombre del archivo con zenity
    filename=$(zenity --entry --title="Guardar portapapeles" --text="Nombre del archivo:")
    if [ -z "$filename" ]; then
        _error "No se proporcionó un nombre de archivo."
        exit 1
    fi
    echo "$clip" >> "$filename"
    _success "Portapapeles pegado en $filename"
else
    f="$1"
    if [ -f "$f" ]; then
        # Si es un archivo, añadir el contenido del portapapeles
        echo "$clip" >> "$f"
        _success "Portapapeles añadido a $f"
    elif [ -d "$f" ]; then
        # Si es una carpeta, crear un archivo con el nombre de la carpeta
        dirname=$(basename -- "$f")
        filename="$f/$dirname"
        echo "$clip" >> "$filename"
        _success "Portapapeles pegado en $filename"
    else
        _error "$f no es un archivo ni una carpeta válida."
        exit 1
    fi
fi
