#!/usr/bin/env sh
# ? description: This script copies the names of the specified files to the clipboard.
# ? usage      : copy_filename [file(s)|directory(s)]

. "$HOME/.bin/_main.sh"

printf '"%s"\n' "$@" | xclip -selection clipboard

# [ $? -eq 0 ] && _success "File names  copied to clipboard." || _error "Failed to copy file names to clipboard."
