#!/usr/bin/env sh
# ? description: Copy the absolute paths of files in the current directory to the clipboard.
# ? usage      : copy_filepath  [file(s)|directory(s)]

. "$HOME/.bin/_main.sh"

for f in "$@"; do
    realpath "$f"
done | sed 's/.*/"&"/' | xclip -selection clipboard


[ $? -eq 0 ] && _success "Paths copied to clipboard." || _error "Failed to copy paths to clipboard."
