#!/usr/bin/env sh
# ? description: Copy the absolute paths of files in the current directory to the clipboard.
# ? usage      : copy_filepath  [file(s)|directory(s)]

. "$HOME/.bin/_main.sh"

for f in "$@"; do
    realpath "$f"
done | sed 's/.*/"&"/' | xclip -selection clipboard


if [ $? -eq 0 ]; then
    _success "File names copied to clipboard."
else
    _error "Failed to copy file names to clipboard."
fi
