#!/usr/bin/env sh
# ? description: pastes the content of the clipboard into a specified file or creates a new file in a specified directory.
# ? usage      : paste_clipboard [file|directory]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

f="$1"
filename=$(basename -- "$f")
name="${filename%.*}"

if [ -f "$f" ]; then
    xclip -selection clipboard -o >> "$f"
elif [ -d "$f" ]; then
    file="$f/$name.txt"
    xclip -selection clipboard -o >> "$file"
else
    _error "No existe o no es ni archivo ni carpeta: $f"
    exit 1
fi
