#!/usr/bin/env python
##? Help : Open dotfiles path on (editor,git,terminal,filemanager) or update symlinks
##? Usage: dotf [-e | --editor] | [-g | --git] | [-t | --terminal] | [-m | --manager] | [-u | --update]

import argparse
from os import path
import subprocess

DOTFILES_PATH = path.join(path.expanduser("~"), ".dotfiles")


git = lambda: subprocess.run(["git", "status"], cwd=DOTFILES_PATH)

editor = lambda: subprocess.run(["code", "."], cwd=DOTFILES_PATH)

terminal = lambda: subprocess.run(["kitty"], cwd=DOTFILES_PATH)

manager = lambda: subprocess.run(["thunar"], cwd=DOTFILES_PATH)

update = lambda: subprocess.run(["dot", "symlinks", "apply"], cwd=DOTFILES_PATH)


def main():
    parser = argparse.ArgumentParser(description="Work with Dotfiles.")
    parser.add_argument("-e", "--editor", action="store_true", help="Open with vscode")
    parser.add_argument("-g", "--git", action="store_true", help="Check git status")
    parser.add_argument(
        "-m", "--manager", action="store_true", help="Open in file manager"
    )
    parser.add_argument(
        "-t", "--terminal", action="store_true", help="Open in terminal"
    )
    parser.add_argument(
        "-u", "--update", action="store_true", help="Update links `dot symlinks apply`"
    )

    args = parser.parse_args()

    if args.update:
        update()
    if args.editor:
        editor()
    if args.git:
        git()
    if args.manager:
        manager()
    if args.terminal:
        terminal()


main()
