#!/usr/bin/env sh
##? help  : Find git repository folders.
##? usage : find_repos [folder]

. "$HOME/.bin/_main.sh"

if [ $# -lt 1 ]; then
	_params_required 1
	exit 1
fi

fd -sHapL -d 2 --regex '\.git$' "$1/" -x echo {//}
