#!/usr/bin/env sh
# ? description: Find git repository folders.
# ? usage      : find_repos [directory]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

fd -sHapL -d 2 --regex '\.git$' "$1/" -x echo {//}
