#!/usr/bin/env sh
# ? description: Initialize a git repository in the current directory.
# ? usage      : init_repo [directory]

. "$HOME/.bin/_main.sh"

if [ -d .git ]; then
    echo "This directory is already a git repository."
else
	mkdir -p "$1"
    git init "$1" -q
    echo "Initializing git repository in $1"
    touch $1/{README,LICENSE,CHANGELOG}.md
    touch $1/.gitignore
    mkdir -p $1/{src,docs,tests,.vscode}
	touch makefile,.env,.env.example
	touch api.http
    $EDITOR $1
fi
