export PATH="$PATH:$DOTFILES_PATH/scripts/convert"
export PATH="$PATH:$DOTFILES_PATH/scripts/filesystem"
export PATH="$PATH:$DOTFILES_PATH/scripts/git"
export PATH="$PATH:$DOTFILES_PATH/scripts/shortcuts"
export PATH="$PATH:$DOTFILES_PATH/scripts/system"
export PATH="$PATH:$DOTFILES_PATH/scripts/yt"
