#!/usr/bin/env sh
#?help : Transform to json format.
#?usage: to_json [.yaml|csv]

. "$HOME/.bin/_main.sh"

if [ $# -lt 1 ]; then
    _params_required 1
    exit 1
fi

archivo="$1"
base="${archivo%.*}"
ext="${archivo##*.}"


if [ "$ext" = "yaml" ] || [ "$ext" = "csv" ]; then
    yq -P -o=json "$archivo" > "$base.json"
else
    _error "Error al convertir"
    exit 0
fi

if [ $? -eq 0 ]; then
    _success "Convertido a yaml"
fi
