#!/usr/bin/env sh
# ? description: Transform to json format.
# ? usage      : to_json [yaml(s)|csv(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
    archivo="$f"
    base="${archivo%.*}"
    ext="${archivo##*.}"

    _log "$f"
    yq -P -o=json "$archivo" > "$base.json" \
    && _success "Convertido a json" || _error "Error al convertir"
done
