#!/usr/bin/env sh
# ? description: Transform file into pdf.
# ? usage      : to_pdf [file(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for archivo in "$@"; do
    nombre="${archivo%.*}"
    _log "$archivo"
    case "$archivo" in
        *.tex) latexmk -quiet -pdf -interaction=nonstopmode "$archivo" && latexmk -c ;;
        *.typ) typst compile "$archivo" ;;
        *.odt | *.docx | *.md) libreoffice --headless --convert-to pdf "$archivo" > /dev/null ;;
        *.png | .jpeg | *.jpg | *.svg) mogrify -strip "$archivo" && img2pdf -o "$nombre.pdf" "$archivo" ;;
        *) pandoc "$archivo" -o $nombre.pdf
    esac
    if [ $? -eq 0 ]; then _success "Compilación completa"; else _error "Error durante la compilación."; fi
done
