#!/usr/bin/env sh
# ? description: Transform to yaml format.
# ? usage      : to_yaml [json(s)|xml(s)|csv(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
    archivo="$f"
    base="${archivo%.*}"
    ext="${archivo##*.}"

    _log "$f"
    yq -P -o=yaml "$archivo" > "$base.yaml" \
    && _success "Convertido a yaml" || _error "Error al convertir"
done
