#!/usr/bin/env sh
# ? description: Transform to yaml format.
# ? usage      : to_yaml [json(s)|xml(s)|csv(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
    archivo="$f"
    base="${archivo%.*}"
    ext="${archivo##*.}"

    if [ "$ext" = "json" ] || [ "$ext" = "xml" ] || [ "$ext" = "csv" ]; then
        yq -P -o=yaml "$archivo" > "$base.yaml"
    else
        _error "Error al convertir"
        exit 0
    fi

    [ $? -eq 0 ] && _success "Convertido a yaml"
done
