#!/usr/bin/env bash
##? help  : Check the conection.
##? usage : check_connection [none]

source "$HOME/.bin/_main.sh"

servidor="8.8.8.8"

if ping -c 3 $servidor > /dev/null 2>&1; then
	_success "La conexión a Internet está bien."
else
	_error "¡Alerta! Problemas de conexión a Internet."
fi
