#!/usr/bin/env sh
# ? description: Decode URL format to human-readable.
# ? usage      : decode_name [file|directory(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

urldecode() {
	decoded_name=$(printf '%b' "${1//%/\\x}")
	mv "$1" "$decoded_name"
}

for element in "$@"; do
	urldecode "$element"
done
