#!/usr/bin/env bash
##? help  : Get your IP address from the command line.
##? usage : my_ip [none]

source "$HOME/.bin/_main.sh"

publica=$(curl -s ifconfig.me)
privada="$(ip addr show | grep 'inet.*brd' | awk '{print $2}' | cut -f1 -d'/' | head -n1)"
echo "{\"publica\":\"$publica\",\"privada\":\"$privada\"}" | jq '.'
curl -s http://ip-api.com/json/$publica | jq '.'

curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -