#!/usr/bin/env bash
# ? description: Short url and copy in clipboard.
# ? usage      : tiny_url [url]

source "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

SHORTENED_URL=$(curl -s -d "url=$1" "http://tinyurl.com/api-create.php")

echo -n $SHORTENED_URL | xclip -selection clipboard
_log $SHORTENED_URL
