#!/usr/bin/env sh
##? help  : Work with Google Drive. Sync folder, upload/download content.
##? usage : drive [ none | folder | file ]

. "$HOME/.bin/rsync/_rsync.sh"

if [ $# -lt 2 ]; then
	_params_required 2
	exit 1
fi

if [ "$1" = "-push" ]; then
	overwrite_cloud Drive drive
elif [ "$1" = "-pull" ]; then
	overwrite_local drive Drive
elif [ "$1" = "-add" ]; then
	add_new_content "drive" $2
elif [ "$1" = "-clone" ]; then
	download_content "drive" $2
else
	exit 1
fi
