#!/usr/bin/env sh
# ? description: Work with Google Drive. Sync folder, upload/download content.
# ? usage      : drive [push|pull|add|clone] [folder]

. "$HOME/.bin/rsync/_rsync.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

if [ "$1" = "push" ]; then
	overwrite_cloud Drive drive
elif [ "$1" = "pull" ]; then
	overwrite_local drive Drive
elif [ "$1" = "add" ]; then
	add_new_content "drive" $2
elif [ "$1" = "clone" ]; then
	download_content "drive" $2
else
	exit 1
fi
