#!/usr/bin/env sh
#?help : Work with MEGA. Sync folder, upload/download content.
#?usage: mega [ none | folder | file ]

. "$HOME/.bin/rsync/_rsync.sh"
if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

if [ "$1" = "push" ]; then
	overwrite_cloud MEGA mega
elif [ "$1" = "pull" ]; then
	overwrite_local mega MEGA
elif [ "$1" = "add" ]; then
	add_new_content "mega" $2
elif [ "$1" = "clone" ]; then
	download_content "mega" $2
else
	exit 1
fi
