#!/usr/bin/env sh
# ? description: export mysql/mariadb database to sql file.
# ? usage      : database_export [database]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

mysqldump -u "$USER" -p "$1" | gzip > "$1.sql.gz" \
&& _success "Database $1 exported to file" || _error "Failed to export database $1"
