#!/usr/bin/env sh
# ? description: Remove database and user.
# ? usage      : database_remove [database]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

DB_NAME=$1

mariadb -u "$USER" -p -e "DROP DATABASE IF EXISTS $DB_NAME; DROP USER IF EXISTS '$DB_NAME'@'localhost';"
