#!/usr/bin/env sh
# ? description: Update system packages: mirrorlist,repos,aur and virus.
# ? usage      : sysupdate [none]

sudo reflector --verbose --score 100 --fastest 10 --number 10 --save /etc/pacman.d/mirrorlist

sudo freshclam
# aura -Syyu
# paru -Sua
paru
