#!/usr/bin/env bash
##? usage : to_jpg [file...]
##? help  : Convert image to jpg format.

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	convert -quality 100 "$f" "$folder/$name.jpg" >/dev/null 2>&1
	if [ $? -eq 0 ]; then
		_success "Convertido: $f -> $name.jpg"
	else
		_error "Error al convertir $f"
	fi
done
