#!/usr/bin/env bash
##? usage : to_jpg [file...]
##? help  : Convert image to jpg format.

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	convert -quality 100 "$f" "$folder/$name.jpg"
	echo "Imagen convertida: $name -] $name.jpg"
done
