#!/usr/bin/env bash
##? usage : to_png [file...]
##? help  : Convert image to png format.

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	convert "$f" -background white "$folder/$name.png"
	echo "Imagen convertida: $name -> $name.png"
done
