#!/usr/bin/env python
##? help  : Build a sxhkdrc shortcut file with yaml file.
##? usage : create_sxhkdrc [none]

from os import path, getenv
from yaml import safe_load as load
from datetime import datetime

def write_keys(mods, keys, file):
    _sxhkd_format = lambda mods, keys: (f"\n{mods}\n\t{keys}")
    if isinstance(keys, str):
        file.writelines(_sxhkd_format(mods, keys))
    else:
        for k, v in keys.items():
            new_mods = f"{mods} + {k}" if mods else k
            write_keys(new_mods, v, file)


if __name__ == "__main__":
    DOTFILES_PATH = getenv("DOTFILES_PATH")
    input_file = path.join(DOTFILES_PATH, "doc", "shortcuts.yaml")
    output_file = path.join(DOTFILES_PATH, "os", "linux", "sxhkd", "sxhkdrc")
    date = datetime.now().strftime("Generated on %Y-%m-%d %H:%M")
    env = "#!/usr/bin/env bash"
    data = load(open(input_file, "r"))["sxhkdrc"]
    with open(output_file, "w") as a:
        a.write(f"{env}\n# {date}\n")
        for mods, keys in data.items():
            write_keys(mods, keys, a)
