#!/usr/bin/env python
##? help  : Build a sxhkdrc shortcut file with yaml file.
##? usage : create_sxhkdrc [none]

from os import path
from yaml import safe_load as load
from datetime import datetime

DOTFILES_PATH = path.join(path.expanduser("~"), ".dotfiles")
input_file = path.join(DOTFILES_PATH, "doc", "shortcuts.yaml")
output_file = path.join(DOTFILES_PATH, "os", "linux", "sxhkd", "sxhkdrc")
_sxhkd_format = lambda mods, keys: (f"\n{mods}\n\t{keys}")

date = datetime.now().strftime("Generated on %Y-%m-%d %H:%M")
env = "#!/usr/bin/env bash"
open(output_file, "w").write(f"{env}\n#{date}\n")

data = load(open(input_file, "r"))
with open(output_file, "a") as a:
    # ; keys are <str> or <dict>
    for mods, keys in data.items():
        try:
            for k, v in data[mods].items():
                a.writelines(_sxhkd_format(f"{mods} + {k}", v))
        except AttributeError:
            a.writelines(_sxhkd_format(mods, keys))
