#!/usr/bin/env sh
##? help  : Print shortcuts from kitty, qtile and sxhkd.
##? usage : get_ shortcuts [none]

. "$HOME/.bin/_main.sh"

_log 'KITTY'
grep '^map' $HOME/.config/kitty/kitty.conf | awk '{for (i=2; i <= NF; i++) printf "%s ", $i; printf "\n"}'

_log 'SXHKDRC'
cat $HOME/.config/sxhkd/sxhkdrc | tail -n +2 | sed ':a;N;$!ba;s/\n\t/: /g'

_log 'QTILE'
grep '^[[:space:]]*\(Key\|Click\|Drag\)' $HOME/.config/qtile/settings/keys.py | sed 's/^[[:space:]]*//'
