#!/usr/bin/env python
# ? description : Print script helper and usage.
# ? usage       : print_scripts [none]

import sys
import re
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from _main import _log

HELP_TAG = r"^\#\s\?"
DOTFILES_PATH = Path.home() / ".bin"

def list_executables(folder: Path = DOTFILES_PATH):
    ejecutables = []
    for file in folder.rglob("*"):
        if ".git" in file.parts:
            continue

        if file.is_file() and file.stat().st_mode & 0o111:
            ejecutables.append(file)

    return ejecutables


def decorate(file_path: Path, help_lines: list):
    print(f"\n\033[33mFile:\033[1m {file_path}\033[0m")
    print("\033[36m" + "\n".join(help_lines) + "\033[0m")


def read_help(file_path: Path):
    help_lines = []

    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            first_line = f.readline().strip()
            if first_line:
                help_lines.append(first_line)

            for line in f:
                if re.match(HELP_TAG, line):
                    help_lines.append(line.strip())
    except Exception as e:
        _log(f"Error al leer {file_path}: {e}")

    if help_lines:
        decorate(file_path, help_lines)


if __name__ == "__main__":
    for executable in list_executables():
        read_help(executable)
