#!/usr/bin/env python
##? help  : Print script helper and usage.
##? usage : print_scripts [none]

import subprocess, sys, os, re

HELP_TAG = r"^\#\#\?"
DOTFILES_PATH = f"{os.path.expanduser('~')}/.bin"


def list_x(folder=DOTFILES_PATH):
    try:
        result = subprocess.run(
            ["fd", ".", DOTFILES_PATH, "-t", "x"],
            capture_output=True,
            text=True,
            check=True,
        )
        out = result.stdout.strip()
        return out.split("\n")
    except subprocess.CalledProcessError as e:
        print(f"Error al ejecutar el comando fd: {e}")
        return []


def decorate(f, h):
    print(f"\n\033[33mFile:\033[1m {f}\033[0m")
    print("\033[36m" + "\n".join(h) + "\033[0m")


def readHelp(file):
    help = []
    bang = ""
    with open(file, "r") as f:
        bang = f.readline().strip()
        help.append(bang)
        help.extend([h.strip() for h in f.readlines() if re.match(HELP_TAG, h)])
    decorate(file, help)


if __name__ == "__main__":
    for e in list_x():
        readHelp(e)
