#!/usr/bin/env sh
# ? description: Convert video to avi format.
# ? usage      : to_avi [video(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	ffmpeg -i "$f" -c:v libxvid -q:v 5 -c:a mp3 -b:a 192k "$folder/$name.avi" >/dev/null 2>&1

	[ $? -eq 0 ] && _success "Convertido: $f -> $name.avi" || _error "Error al convertir $f"
done
