#!/usr/bin/env sh
#?help : Convert video to avi format.
#?usage: to_avi [file...]

. "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	ffmpeg -i "$f" -c:v libxvid -q:v 5 -c:a mp3 -b:a 192k "$folder/$name.avi" >/dev/null 2>&1

	if [ $? -eq 0 ]; then
		_success "Convertido: $f -> $name.avi"
	else
		_error "Error al convertir $f"
	fi
done
