#!/usr/bin/env sh
# ? description: Convert video to mp4 format.
# ? usage      : to_mp4 [video(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	ffmpeg -i "$f" -codec:v copy -codec:a mp3 -q:a 0

	ffmpeg -i "$f" -c:v libx264 -preset slow -crf 23 -c:a aac -b:a 192k "$folder/$name.mp4" >/dev/null 2>&1

	[ $? -eq 0 ] && _success "Convertido: $f -> $name.mp4" || _error "Error al convertir $f"
done
