#!/usr/bin/env sh
# ? description: Convert video to mkv format.
# ? usage      : to_mkv [video(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	ffmpeg -i "$f" -c:v libx265 -preset slow -crf 23 -c:a aac -b:a 192k "$folder/$name.mkv" >/dev/null 2>&1

	[ $? -eq 0 ] && _success "Convertido: $f -> $name.mkv" || _error "Error al convertir $f"
done
