#!/usr/bin/env sh
# ? description: Convert video to mp4 format.
# ? usage      : to_mp4 [video(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
    _log "$f"
	ffmpeg -y -i "$f" -c:v libx265 -crf 23 -preset medium -c:a aac -b:a 192k "$folder/$name.mp4" >/dev/null 2>&1 \
    && _success "Convertido $f" || _error "Error al convertir $f"
done
