#!/usr/bin/env sh
#?help  : Convert video to mp4 format.
#?usage : to_mp4 [file...]

. "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	ffmpeg -i "$f" -codec:v copy -codec:a mp3 -q:a 0

	ffmpeg -i "$f" -c:v libx264 -preset slow -crf 23 -c:a aac -b:a 192k "$folder/$name.mp4" >/dev/null 2>&1

	if [ $? -eq 0 ]; then
		_success "Convertido: $f -> $name.mp4"
	else
		_error "Error al convertir $f"
	fi
done
