#!/usr/bin/env bash
##? usage : enable_service [service]
##? help  : Start service, start service on init.

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

sudo systemctl start $1
sudo systemctl enable $1
_log "Inicializado $1"
