#!/usr/bin/env bash
##? usage : mount_disk [name]
##? help  : Mount the partition with LABEL on the media folder.

source "$DOTFILES_PATH/scripts/_main.sh"

label=$(lsblk -o LABEL | grep "$1")
device=$(blkid -l -o device -t LABEL="$label")
d="/run/media/$USER/$label"
sudo mkdir -p "$d" && sudo mount "$device" "$d"
_success "Montado: $device -> $d"
