#!/usr/bin/env bash
##? usage : my_ip [empty]
##? help  : Get your IP address from the command line.

source "$DOTFILES_PATH/scripts/_main.sh"

publica=$(curl -s ifconfig.me)
privada="$(ip addr show | grep 'inet.*brd' | awk '{print $2}' | cut -f1 -d'/' | head -n1)"
echo "{\"publica\":\"$publica\",\"privada\":\"$privada\"}" | jq '.'
curl -s http://ip-api.com/json/$publica | jq '.'
