#!/usr/bin/env bash
##? help  : Start service.
##? usage : enable_service [service]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

sudo systemctl start $1
_log "Inicializado $1"
