#!/usr/bin/env sh
# ? description: Enable service on init.
# ? usage      : enable_service [service]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

sudo systemctl enable $1
_log "Enabled $1"
