#!/usr/bin/env sh
# ? description: Start service.
# ? usage      : enable_service [service]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

sudo systemctl start $1
_log "Inicializado $1"
