#!/usr/bin/env sh
# ? description: Convert image to jpg format.
# ? usage      : to_jpg [image(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	magick -quality 100 "$f" "$folder/$name.jpg" >/dev/null 2>&1
	[ $? -eq 0 ] && _success "Convertido: $f -> $name.jpg" || _error "Error al convertir $f"
done
