#!/usr/bin/env sh
# ? description: Convert image to png format.
# ? usage      : to_png [image(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
    _log "$f"
	magick "$f" -strip -background white "$folder/$name.png" >/dev/null 2>&1 \
    && _success "Convertido: $f -> $name.png" || _error "Error al convertir: $f"
done
