#!/usr/bin/env bash
# ? description: Convert image to webp format.
# ? usage      : to_webp [image(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	cwebp -q 100 -m 6 -pass 10 "$f" -o "$folder/$name.webp" >/dev/null 2>&1
	[ $? -eq 0 ] && _success "Convertido: $f -> $name.webp" || _error "Error al convertir: $f"
done
