#!/usr/bin/env bash
#?help : Convert image to webp format.
#?usage: to_webp [file...]

. "$HOME/.bin/_main.sh"

if [ $# -lt 1 ]; then
	_params_required 1
	exit 1
fi

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	cwebp -q 100 -m 6 -pass 10 "$f" -o "$folder/$name.webp" >/dev/null 2>&1
	if [ $? -eq 0 ]; then
		_success "Convertido: $f -> $name.webp"
	else
		_error "Error al convertir: $f"
	fi
done
