#!/usr/bin/env sh
# ? description: Create a 50G qcow file in [name].
# ? usage      : create_qcow2 [name]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

vm=$1

mkdir -p "$vm"
qemu-img create -f qcow2 "$vm/$vm.qcow2" 50G

[ $? -eq 0 ] && _success "Disc created" || _error "Error on create disc"
