#!/usr/bin/env sh
# ? description: Extract ova file.
# ? usage      : extract_ova [ova]

. "$HOME/.bin/_main.sh"

archivo=$1
carpeta="${archivo%.*}"
mkdir -p $carpeta
tar -xvf "$archivo" -C $carpeta

if [ $? -eq 0 ]; then
    _success "File extracted"
else
    _error "Error on extraction"
fi
