#!/usr/bin/env sh
# ? description: Extract ova file.
# ? usage      : extract_ova [ova]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
    _log "Extraer ova $f"
    carpeta="${f%.*}"
    mkdir -p $carpeta
    tar -xvf "$f" -C $carpeta \
    && _success "OVA extraida en $carpeta" || _error "Error al extraer la ova"
done
