#!/usr/bin/env sh
# ? description: Extract ova file.
# ? usage      : extract_ova [ova]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

archivo=$1
carpeta="${archivo%.*}"
mkdir -p $carpeta
tar -xvf "$archivo" -C $carpeta

[ $? -eq 0 ] && _success "File extracted" || _error "Error on extraction"
