#!/bin/sh
# ? description: Mount img file.
# ? usage      : mount_img [.img]

. "$HOME/.bin/_main.sh"
if [ $# -lt 1 ]; then
    _params_required 1
    exit 1
fi

FILE="$1"

# Crear el loop device
dev=$(udisksctl loop-setup -f "$FILE" | awk '/Created/ {print $5}')

if [ -n "$dev" ]; then
    udisksctl mount -b "$dev"
    _success "Dispositivo montado: $dev"
else
    _error "Error al crear dispositivo loop"
    exit 1
fi
