#!/usr/bin/env bash
##? help  : Generate password with lengh 20.
##? usage : passwords [none]

longitud=20
caracteres="A-Za-z0-9@#$"

contrasena=$(openssl rand -base64 48 | tr -dc "$caracteres" | head -c "$longitud")

echo "Contraseña generada: $contrasena"
