#!/usr/bin/env bash
##? Help : Print script helper and usage.
##? Usage: print_scripts <empty>

path="$DOTFILES_PATH/scripts"

executable=$(fd . $path -t x)

for element in "${executable[@]}"; do
	bat -l sh -r 1:3 $element
done
