#!/usr/bin/env bash
##? usage : print_scripts [empty]
##? help  : Print script helper and usage.

path="$DOTFILES_PATH/scripts"

executable=$(fd . $path -t x)

for element in "${executable[@]}"; do
	bat -l sh -r 1:3 $element
done
