#!/usr/bin/env sh
##? help  : Save clipboard in file named clipboard_date.
##? usage : save_clipboard [none]

timestamp=$(date +%s)

echo "$(xclip -selection clipboard -o)" >"clipboard_$timestamp.txt"
