#!/usr/bin/env bash
##? usage : tiny_url [url]
##? help  : Short url and copy in clipboard.
source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

SHORTENED_URL=$(curl -s -d "url=$1" "http://tinyurl.com/api-create.php")

echo -n $SHORTENED_URL | xclip -selection clipboard
_log $SHORTENED_URL
