#!/usr/bin/env bash
##? usage : uuid [empty]
##? help  : Generate uuid code and save in clipboard.

source "$DOTFILES_PATH/scripts/_main.sh"

uuid=$(uuidgen | tr '[:upper:]' '[:lower:]')
echo -n $uuid | xclip -selection clipboard
_log $uuid
