#!/usr/bin/env python
# ? help : Rename file by date creation. Rename file to "name_YYYY-MM-DD.extension".
# ? usage: rename_by_date [folder|empty]

from pathlib import Path
from datetime import datetime


def rename_by_date(file):
    file = Path(file)
    name, extension = file.stem, file.suffix
    timestamp = file.stat().st_ctime

    date = datetime.fromtimestamp(timestamp).strftime("%Y-%m-%d")
    new_name = f"{name}_{date}{extension}"
    file.rename(new_name)
    print(f"[*] mv {file} to {new_name}")


def rename_by_num(file):
    extension = file.suffix
    new_name = f"{folder_name}_{i}{extension}"
    new_path = folder / new_name
    if new_path != file:
        file.rename(new_path)
        print(f"[*] mv {file.name} -> {new_name}")
    else:
        print(f"[!] {new_path} exists")


if __name__ == "__main__":
    from sys import argv

    folder = Path(argv[1]) if len(argv) > 1 else Path.cwd()
    folder_name = folder.name

    files = sorted(
        [f for f in folder.iterdir() if f.is_file()], key=lambda f: f.stat().st_mtime
    )

    for i, file in enumerate(files, start=1):
        rename_by_date(file)
        # rename_by_num(file)
