#!/usr/bin/env python
# ? description : Rename file by date creation. Rename file to "name_YYYY-MM-DD.extension".
# ? usage       : rename_sequential [directory|none]

from pathlib import Path


def _rn(old_name, new_name):
    if new_name != old_name:
        old_name.rename(new_name)
        print(f"mv {old_name.name} -> {new_name}")
        return  True
    return False


def name_with_date(files: list[Path]) -> None:
    from datetime import datetime

    for file in files:
        file = Path(file)
        name, extension = file.stem, file.suffix
        timestamp = file.stat().st_ctime
        date = datetime.fromtimestamp(timestamp).strftime("%Y-%m-%d")
        _rn(file, f"{name}_{date}{extension}")


def with_numeric_sequence(files: list[Path], with_folder: bool = False) -> None:
    l = len(str(len(files)))
    for i, file in enumerate(files, start=1):
        extension = file.suffix
        i = str(i).zfill(l)
        if with_folder:
            i = f"{file.parent.name} - {i}"
        _rn(file, f"{folder}/{i}{extension}")


if __name__ == "__main__":
    from sys import argv
    from os import chdir

    folders = argv[2:] or [Path.cwd()]

    for folder in folders:
        chdir(folder)
        files = sorted(
            [f for f in Path.cwd().iterdir() if f.is_file()],
            # key=lambda f: f.stat().st_mtime,
            key=lambda f: f.name,
        )
        if   argv[1] == "-d": name_with_date(files)
        elif argv[1] == "-n": with_numeric_sequence(files,True)
        elif argv[1] == "-s": with_numeric_sequence(files,False)
