#!/usr/bin/env python
# ? description : Rename file with folder_name + num.
# ? usage       : rename_by_folder [folder(s)|none]
# ? example     : folder/name.txt => folder/folder - 1.txt

from pathlib import Path


def aplicar_rename(nombres: tuple, ficheros: list[Path]) -> None:
    actual, nuevo = nombres
    for fichero_str in ficheros:
        fichero_str = Path(fichero_str)
        if fichero_str.stem == actual:
            nuevo_path = fichero_str.with_name(nuevo + fichero_str.suffix)

            if not nuevo_path.exists():
                print(f"renamed '{fichero_str.name}' -> '{nuevo_path.name}'")
                fichero_str.rename(nuevo_path)


def rellenar_huecos(faltantes: set, erroneos: set) -> list:
    l1, l2, r = list(faltantes), list(erroneos), []
    while l1 and l2:
        r.append((l2.pop(-1), l1.pop(0)))
    return r


def extraer_numero_final(path: Path) -> int | None:
    import re

    m = re.search(r"(\d+)$", path.stem)
    return int(m.group(1)) if m else None


def actualizar_ficheros():
    files = sorted(
        [Path(f) for f in Path.cwd().iterdir() if f.is_file()],
        key=lambda p: p.name.lower(),
    )
    ficheros_actuales = [Path(f).stem for f in files]
    return files, ficheros_actuales


def rename_by_folder(files: list[Path]) -> None:
    # ? ex: 001.aaa 002.aaa ...
    def rename_numerados():
        files, ficheros_actuales = actualizar_ficheros()
        if all(v.isdigit() for v in ficheros_actuales):
            for v in ficheros_actuales:
                aplicar_rename((v, f"{folder_name} - {v.zfill(ancho)}"), files)
            return

    # ? AAA_1.aaa DDD-3.aaa ...
    def rename_con_numeracion():
        files, ficheros_actuales = actualizar_ficheros()
        for f in ficheros_actuales:
            fichero = Path(f)
            numero = extraer_numero_final(fichero)
            if numero is not None:
                aplicar_rename(
                    (f, f"{folder_name} - {str(numero).zfill(ancho)}"), files
                )

    def rename_generico():
        files, ficheros_actuales = actualizar_ficheros()
        ficheros_ideales = [
            f"{folder_name} - {str(i+1).zfill(ancho)}" for i in range(len(files))
        ]
        ficheros_actuales = [Path(f).stem for f in files]
        faltantes = sorted(set(ficheros_ideales) - set(ficheros_actuales))
        erroneos = sorted(set(ficheros_actuales) - set(ficheros_ideales))

        for f in rellenar_huecos(faltantes, erroneos):
            aplicar_rename(f, files)

    rename_numerados()
    rename_con_numeracion()
    rename_generico()


if __name__ == "__main__":
    from sys import argv
    from os import chdir

    folders = argv[1:] or [Path.cwd()]
    for folder in folders:
        folder = Path(folder)
        chdir(folder)
        folder_name = folder.name
        files, _ = actualizar_ficheros()
        ancho = len(str(len(files)))
        rename_by_folder(files)
