#!/usr/bin/env sh
# ? description: Convert a file to vdi format.
# ? usage      : disk2vdi [disk(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
    filename=$(basename -- "$f")
    name="${filename%.*}"

    _log "$f"
    qemu-img convert -O vdi "$filename" "$name".vdi \
    && _success "$filename => vdi" || _error "Error on conversion"
done
