#!/usr/bin/env sh
# ? description: Convert a file to qcow2 format.
# ? usage      : disk2qcow2 [disk(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
    filename=$(basename -- "$f")
    name="${filename%.*}"

    _log "$f"
    qemu-img convert -O qcow2 -c "$1" "$name".qcow2 \
    && _success "$filename => qcow2" || _error "Error on conversion"
done
