#!/usr/bin/env sh
# ? description: Convert a file to qcow2 format.
# ? usage      : to_qcow2 [disk(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
    filename=$(basename -- "$f")
    name="${filename%.*}"

    qemu-img convert -O qcow2 -c "$1" "$name".qcow2
    [ $? -eq 0 ] && _success "File converted to qcow2" || _error "Error on conversion"
done
