#!/usr/bin/env sh
# ? description: Convert a file to qcow2 format.
# ? usage      : to_qcow2 [disk(s)]

. "$HOME/.bin/_main.sh"

if [ $# -lt 1 ]; then
	_params_required 1
	exit 1
fi

for f in "$@"; do
    filename=$(basename -- "$f")
    name="${filename%.*}"

    qemu-img convert -O qcow2 -c "$1" "$name".qcow2

    if [ $? -eq 0 ]; then
        _success "File converted to qcow2"
    else
        _error "Error on conversion"
    fi
done
