#!/usr/bin/env sh
#?help : Convert a file to vdi format.
#?usage: to_vdi [filename]

. "$HOME/.bin/_main.sh"

if [ $# -lt 1 ]; then
	_params_required 1
	exit 1
fi

filename=$(basename -- "$1")
name="${filename%.*}"

qemu-img convert -O vdi $filename $name.vdi

if [ $? -eq 0 ]; then
    _success "File converted to vdi"
else
    _error "Error on conversion"
fi
