#!/usr/bin/env sh
# ? description: Convert audio to aac format.
# ? usage      : to_aac [audio(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
    _log "$f"
    ffmpeg -y -i "$f" -c:a aac -b:a 192k "$folder/$name.aac" >/dev/null 2>&1 \
    && _success "Convertido: $f -> $name.aac" || _error "Error al convertir $f"
done
