#!/usr/bin/env sh
# ? description: Convert audio to m4a/mp4 format.
# ? usage      : to_m4a [audio(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	ffmpeg -i "$f" -c:v copy -c:a aac -strict experimental -b:a 192k "$folder/$name.m4a" >/dev/null 2>&1

	[ $? -eq 0 ] && _success "Convertido: $f -> $name.m4a" || _error "Error al convertir $f"
done
