#!/usr/bin/env sh
# ? description: Convert audio to mp3 format.
# ? usage      : to_mp3 [audio(s)]

. "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	ffmpeg -i "$f" -codec:v copy -codec:a mp3 -q:a 0 "$folder/$name.mp3" >/dev/null 2>&1
	if [ $? -eq 0 ]; then
		_success "Convertido: $f -> $name.mp3"
	else
		_error "Error al convertir $f"
	fi
done
