#!/usr/bin/env sh
# ? description: Convert audio to mp3 format.
# ? usage      : to_mp3 [audio(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	ffmpeg -i "$f" -codec:v copy -codec:a mp3 -q:a 0 "$folder/$name.mp3" >/dev/null 2>&1
	[ $? -eq 0 ] && _success "Convertido: $f -> $name.mp3" || _error "Error al convertir $f"
done
