#!/usr/bin/env sh
# ? description: Convert audio to ogg format.
# ? usage      : to_ogg [audio(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
    _log "$f"
    ffmpeg -y -i "$f" -c:a libvorbis -q:a 5 "$folder/$name.ogg" >/dev/null 2>&1 \
    && _success "Convertido: $f -> $name.ogg" || _error "Error al convertir $f"
done
