#!/usr/bin/env sh
# ? description: Convert audio to wav format.
# ? usage      : to_wav [audio(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
    _log "$f"
    ffmpeg -y -i "$f" -c:a pcm_s16le "$folder/$name.wav" >/dev/null 2>&1\
    && _success "Convertido: $f -> $name.wav" || _error "Error al convertir $f"
done
