#!/usr/bin/env sh
# ? description: Tar without compress.
# ? usage      : archive_separated [file(s)|directory(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for i in "$@"; do
	input="$i"
	name=$(basename "$input")
	if [ -f "$input" ]; then
		name="${name%.*}"
	fi
	compress_folder=$name

	apack "$compress_folder.tar" "$input"

	[ $? -eq 0 ] && _success "Archivo $compress_folder creado correctamente." || _error "Error al crear el archivo."
done
