#!/usr/bin/env sh
# ? description: Make backup of files or directories to a compressed file.
# ? usage      : backup [file(s)|directory(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

if [ $# -gt 1 ]; then
    parent_folder=$(basename "$PWD")
	compress_folder="${parent_folder}_$(date +%Y%m%d%H%M)"
else
	input="$1"
	name=$(basename "$input")
	if [ -f "$input" ]; then
		name="${name%.*}"
	fi
	compress_folder=$name
fi

apack "$compress_folder.tar.xz" "$@"

[ $? -eq 0 ] && _success "Backup $compress_folder creado correctamente." || _error "Error al crear el backup."
