#!/usr/bin/env sh
# ? description: Make backup of files or directories to a compressed file.
# ? usage      : backup_separated [file(s)|directory(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for i in "$@"; do
	input="$i"
	name=$(basename "$input")
	if [ -f "$input" ]; then
		name="${name%.*}"
	fi
	compress_folder=$name

	apack "$compress_folder.tar.xz" "$input"

	[ $? -eq 0 ] && _success "Backup $compress_folder creado correctamente." || _error "Error al crear el backup."
done
