#!/usr/bin/env sh
# ? description: Compress files or directories into a separated files.
# ? usage      : compress_separated [file(s)|directory(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

for i in "$@"; do
	input="$i"
	name=$(basename "$input")
	if [ -f "$input" ]; then
		name="${name%.*}"
	fi
	compress_folder=$name

    APACK_CMD="7z a -t7z -mx=9" apack "$compress_folder.7z" "$input"

	if [ $? -eq 0 ]; then _success "'$compress_folder' comprimido correctamente."; else _error "Error al comprimir."; fi
done
