#!/usr/bin/env sh
# ? description: Decompress files or directories from a compressed file.
# ? usage      : decompress [file(s)|directory(s)]

. "$HOME/.bin/_main.sh"

for i in "$@"; do
    file="$1"
    base="${file%%.*}"
    echo $base

    [ -d "$base" ] && aunpack -X "$base" "$file" || aunpack "$file"
	[ $? -eq 0 ] && _success "Archivo '$compress_folder' descomprimido" || _error "Error al descomprimir el archivo."
done
