#!/usr/bin/env sh
##? help  : Extract a compressed file.
##? usage : extract [file]

. "$HOME/.bin/_main.sh"

if [ $# -lt 1 ]; then
	_params_required 1
	exit 1
fi

file=$1
case $file in
*.7z) 7z x $file ;;
*.gz) gunzip $file ;;
*.bz2) bunzip2 $file ;;
*.zip) unzip $file ;;
*.tar) tar $file ;;
*) _error "Not compressed file" ;;
esac
