#!/usr/bin/env sh
# ? description: create a playlist with mp3 and mp4 files in folder.
# ? usage      : create_playlist [directory]

. "$HOME/.bin/_main.sh"


path="${1:-$PWD}"
path="$(realpath "$path")"

folder="${2:-$(basename "$path")}"

name="playlist_$folder.m3u"
echo -e "#!/usr/bin/vlc\n# $(date)\n# $path\n" >"$name"
fd -t f --regex "mp\d$" -d1 "$path" >>"$name"
