#!/usr/bin/env sh
##? help  : Record screen.
##? usage : screen_recorder [none]

output="$(xdg-user-dir VIDEOS)/screen_recorder-$(date +'%Y-%m-%d_%H-%M-%S').mp4"
ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 $output
