#!/usr/bin/env bash
##? help  : Convert audio to m4a/mp4 format.
##? usage : to_m4a [file...]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	ffmpeg -i "$f" -c:v copy -c:a aac -strict experimental -b:a 192k "$folder/$name.m4a" >/dev/null 2>&1

	if [ $? -eq 0 ]; then
		_success "Convertido: $f -> $name.m4a"
	else
		_log "Error al convertir $f"
	fi
done
