#!/usr/bin/env sh
# ? description: Make folder by file_name and move files.
# ? usage      : organize_by_name [none]
# ? example    : 'name - 1', 'name - 2' moved to folder 'name'


separator=(" - " " _ ")

for sep in "${separator[@]}"; do
    fd "$sep" -tf | while IFS= read -r file; do
        name="${file%%$sep*}"
        mkdir -p "$name"
        mv -i "$file" "$name/"
    done
done
