#!/usr/bin/env python
# ? description : Move files to folder by MIME.
# ? usage       : organize_by_type [directory|none]

import sys
from pathlib import Path
from subprocess import check_output

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from _main import _message

home = Path.home()
xdg_user_dir = lambda type: check_output(["xdg-user-dir", type.upper()], universal_newlines=True).strip()

mimeTypes = {
    # f"{home}/Virtual Machines": ["octet-stream", "x-qemu-disk", "vdi", "ovf", "ova", "iso"],
    f"{home}/.ssh": ["x-pem-file", "x-ssh-public-key"],
    xdg_user_dir("TEMPLATES"): ["template", "desktop"],
    xdg_user_dir("MUSIC"): ["audio"],
    xdg_user_dir("USERFONTS"): ["font"],
    xdg_user_dir("DOCUMENTS"): ["pdf", "opendocument", "zip", "epub", "md"],
    xdg_user_dir("PICTURES"): ["image", "gbr"],
    xdg_user_dir("VIDEOS"): ["video"],
}

get_mime_type = lambda file: check_output( ["file", "--mime-type", "-b", file], text=True ).strip()


def organize_folder(folder: list[Path]):
    for file in folder:
        file = Path(file)
        extension = "".join(file.suffixes)[1:]
        mime = get_mime_type(file)
        for dir, types in mimeTypes.items():
            if any(t in mime for t in types) or extension in types:
                target_path = Path(f"{dir}/{file.name}")

                if target_path.exists():
                    _message.error(f"{file.name} ya existe en {dir}")
                    break

                try:
                    file.rename(target_path)
                    _message.success(f"{file.name} -> {dir}")
                except Exception as e:
                    _message.error(f"Error al mover {file.name}: {e}")
                finally:
                    break


if __name__ == "__main__":
    from sys import argv

    folder = Path(argv[1]) if len(argv) > 1 else Path.cwd()
    files = [file for file in folder.iterdir() if file.is_file()]

    if not files:
        _message.log("No se encontraron archivos para organizar")
        sys.exit(0)
    organize_folder(files)
