#!/usr/bin/env sh
# ? description: Make folder by file_name and move files.
# ? usage      : organize_by_name [none]
# ? example    : 'name - 1', 'name - 2' moved to folder 'name'


fd ' - ' -tf | while IFS= read -r file; do
    name="${file%% - *}"
    mkdir -p "$name"
    mv -i "$file" "$name/"
done
