#!/usr/bin/env sh

notify(){
	echo $1
	notify-send --expire-time 0 "Pomodoro" "$(date +'%H:%M:%S') | $1"
	paplay "/usr/share/sounds/freedesktop/stereo/service-login.oga"
}

# Configuración
WORK_TIME=25 # minutos de trabajo
BREAK_TIME=$((WORK_TIME / 5))  # descanso corto=work time / 5
LONG_BREAK=$((BREAK_TIME * 2))
REPS=6 # número de Pomodoros
LONG_BREAK_INTERVAL=4  # cada X Pomodoros, descanso largo

i=1
while [ $i -le $REPS ]; do
    notify "💪 Pomodoro $i de $REPS iniciado: $WORK_TIME minutos de trabajo."
    sleep $((WORK_TIME * 60))

    # Decidir tipo de descanso
    if [ $((i % LONG_BREAK_INTERVAL)) -eq 0 ]; then
        notify "🛌 Descanso largo: $LONG_BREAK minutos."
        sleep $((LONG_BREAK * 60))
    else
        notify "⏰ Descanso corto: $BREAK_TIME minutos."
        sleep $((BREAK_TIME * 60))
    fi
    notify "✅ Pomodoro $i terminado."
    i=$((i + 1))
done

notify "🎉 ¡Todos los Pomodoros completados!"
