#!/usr/bin/env sh
source "$HOME/.bin/_main.sh"

video_regex='^https?:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}(\/\S*)?$'
playlist_regex='^(https?:\/\/)?(www\.)?(youtube\.com\/|youtu\.be\/)(playlist\?|list=)([^#\&\?\n]+)'
