#!/usr/bin/env sh
# ? description: Save clipboard un file to download.
# ? usage      : to_yt-dlp [none]

source "_yt-dlp.sh"

file="$(xdg-user-dir DOWNLOAD)/yt.yt-dlp"
echo -e "# $(date +%Y-%m-%d-%H:%M:%S)\n$(xclip -selection clipboard -o)" >>$file

if [ $? -eq 0 ]; then
	_success "YT download file list is updated"
else
	_error "Error clipboard"
fi
