#!/usr/bin/env sh
# ? description: Save clipboard un file to download.
# ? usage      : to_yt-dlp [none]

source "_yt-dlp.sh"

file="$(xdg-user-dir DOWNLOAD)/yt.yt-dlp"
echo -e "# $(date +%Y-%m-%d-%H:%M:%S)\n$(xclip -selection clipboard -o)" >>$file

[ $? -eq 0 ] && _success "YT download file list is updated" || _error "Error clipboard"
