#!/usr/bin/env bash
##? usage : yt-audio-file [file]
##? help  : Download all audio from url save in file.

yt-dlp -i --no-playlist \
	--embed-metadata --embed-thumbnail \
	--audio-quality 0 -f bestaudio -x --audio-format mp3 \
	-o "$(xdg-user-dir DOWNLOAD)/%(title)s.%(ext)s" \
	--batch-file $@
