#!/usr/bin/env bash
# ? description: Download audio.
# ? usage      : yt-audio [url|file]

source "_yt-dlp"

[ $# -lt 1 ] && _params_required 1 && exit 1

_log "Descargando audio $1"

# Opciones comunes para yt-dlp
yt_dlp_opts=(
	-i
	--embed-metadata --embed-thumbnail
	--progress
	--audio-quality 0 -f bestaudio -x --audio-format mp3
)
if [[ $1 =~ $playlist_regex ]]; then
	yt-dlp -w "${yt_dlp_opts[@]}" \
		-o "$(xdg-user-dir DOWNLOAD)/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" $@
elif [[ $1 =~ $video_regex ]]; then
	yt-dlp --no-playlist "${yt_dlp_opts[@]}" --quiet \
		-o "$(xdg-user-dir DOWNLOAD)/%(title)s.%(ext)s" $@
elif [ -f "$1" ]; then
	yt-dlp --no-playlist "${yt_dlp_opts[@]}" \
		-o "$(xdg-user-dir DOWNLOAD)/%(title)s.%(ext)s" \
		--batch-file $@
fi

[ $? -eq 0 ] && _success "Audio descargado" || _error "Error al descargar"
