#!/usr/bin/env bash
##? usage : yt-audio-list [url]
##? help  : Download audio playlist.

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

yt-dlp -w -i \
	--embed-metadata --embed-thumbnail \
	--quiet --progress \
	--audio-quality 0 -f bestaudio -x --audio-format mp3 \
	-o "$(xdg-user-dir DOWNLOAD)/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" $@

if [ $? -eq 0 ]; then
	_success "Playlist de audio descargada"
else
	_error "Error al descargar"
fi
