#!/usr/bin/env bash
##? Help : Download audio
##? Usage: yt-audio <url>

yt-dlp -i --no-playlist \
	--embed-metadata --embed-thumbnail \
	--audio-quality 0 -f bestaudio -x --audio-format mp3 \
	-o "$(xdg-user-dir DOWNLOAD)/%(title)s.%(ext)s" $@
