#!/usr/bin/env bash
# ? description: Download episode from serie.
# ? usage      : yt-episode [url|file]

source "_yt-dlp"

[ $# -lt 1 ] && _params_required 1 && exit 1

_log "Descargando episodio $1"

# Opciones comunes para yt-dlp
yt_dlp_opts=(
	-i --no-playlist
	--embed-metadata --embed-thumbnail
	--quiet --progress
    --windows-filenames
	-f "bv*+ba/b" -S "res:1080,ext:mp4:m4a"
	--parse-metadata "%(series)s S%(season_number)02dE%(episode_number)02d:%(title)s"
	-o "$(xdg-user-dir DOWNLOAD)/%(series)s/%(series)s - S%(season_number)02d/%(title)s.%(ext)s"
)

if [[ $1 =~ $video_regex ]]; then
	yt-dlp "${yt_dlp_opts[@]}" "$@"
elif [[ -f "$1" ]]; then
	yt-dlp "${yt_dlp_opts[@]}" --batch-file "$@"
elif [ -f "$1" ]; then
    while IFS= read -r line; do
		[ -z "$line" ] && continue
		yt-episode "$line"
	done < "$1"
fi

[ $? -eq 0 ] && _success "Episodio descargado" || _error "Error al descargar"
