#!/usr/bin/env bash
##? help  : Download episode from serie.
##? usage : yt-episode [url|file]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

if [[ $1 =~ $video_regex ]]; then
	yt-dlp -i --no-playlist \
		--embed-metadata --embed-thumbnail \
		--quiet --progress \
		-f "bv*+ba/b" -S "res:1080,ext:mp4:m4a" \
		--parse-metadata "%(series)s S%(season_number)02dx%(episode_number)02d:%(title)s" \
		-o "$(xdg-user-dir DOWNLOAD)/%(series)s/%(series)s - S%(season_number)02d/%(title)s.%(ext)s" $@
elif [ -f "$1" ]; then
	yt-dlp -i --no-playlist \
		--embed-metadata --embed-thumbnail \
		--quiet --progress \
		--parse-metadata "%(series)s S%(season_number)02dx%(episode_number)02d:%(title)s" \
		-f "bv*+ba/b" -S "res:1080,ext:mp4:m4a" \
		-o "$(xdg-user-dir DOWNLOAD)/%(series)s/%(series)s - S%(season_number)02d/%(title)s.%(ext)s" \
		--batch-file $@
fi

if [ $? -eq 0 ]; then
	_success "Capitulo descargado"
else
	_error "Error al descargar"
fi
