#!/usr/bin/env bash
##? help  : Download song.
##? usage : yt-music [url|file]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

if [[ $1 =~ $playlist_regex ]]; then
	yt-dlp -w -i \
		--embed-metadata --embed-thumbnail \
		--progress \
		--audio-quality 0 -f bestaudio -x --audio-format mp3 \
		-o "$(xdg-user-dir DOWNLOAD)/%(playlist)s/%(title)s.%(ext)s" "$@" \
		--parse-metadata "title:%(artist)s - %(title)s" \
		--parse-metadata "artist:%(artist)s" \
		--parse-metadata "album:%(album)s" \
		--parse-metadata "date:%(year)s"
elif [[ $1 =~ $video_regex ]]; then
	yt-dlp -i --no-playlist \
		--embed-metadata --embed-thumbnail \
		--quiet --progress \
		--audio-quality 0 -f bestaudio -x --audio-format "mp3" \
		-o "$(xdg-user-dir DOWNLOAD)/%(title)s - %(artist)s.%(ext)s" "$@" \
		--parse-metadata "title:%(artist)s - %(title)s" \
		--parse-metadata "artist:%(artist)s" \
		--parse-metadata "album:%(album)s" \
		--parse-metadata "date:%(year)s"
elif [[ -f "$1" ]]; then
	yt-dlp -i --no-playlist \
		--embed-metadata --embed-thumbnail \
		--progress \
		--audio-quality 0 -f bestaudio -x --audio-format "mp3" \
		-o "$(xdg-user-dir DOWNLOAD)/%(playlist)s/%(title)s - %(artist)s.%(ext)s" \
		--batch-file "$@" \
		--parse-metadata "title:%(artist)s - %(title)s" \
		--parse-metadata "artist:%(artist)s" \
		--parse-metadata "album:%(album)s" \
		--parse-metadata "date:%(year)s"
fi

if [ $? -eq 0 ]; then
	_success "Cancion descargada"
else
	_error "Error al descargar"
fi
