#!/usr/bin/env bash
# ? description: Download song.
# ? usage      : yt-music [url|file]

source "_yt-dlp"

[ $# -lt 1 ] && _params_required 1 && exit 1

_log "Descargando musica $1"

# Opciones comunes para yt-dlp
yt_dlp_opts=(
	-i
	--embed-metadata --embed-thumbnail
	--quiet --progress
	--windows-filenames
	--audio-quality 0 -f bestaudio -x --audio-format mp3
	--parse-metadata "title:%(artist)s - %(title)s"
	--parse-metadata "artist:%(artist)s"
	--parse-metadata "album:%(album)s"
	--parse-metadata "date:%(year)s"
)
if [[ $1 =~ $playlist_regex ]]; then
	yt-dlp -w "${yt_dlp_opts[@]}" \
		-o "$(xdg-user-dir DOWNLOAD)/%(playlist)s/%(title)s.%(ext)s" "$@"
elif [[ $1 =~ $video_regex ]]; then
	yt-dlp --no-playlist "${yt_dlp_opts[@]}" \
		-o "$(xdg-user-dir DOWNLOAD)/%(title)s - %(artist)s.%(ext)s" "$@"
elif [[ -f "$1" ]]; then
	while IFS= read -r line; do
		[ -z "$line" ] && continue
		yt-music "$line"
	done < "$1"
fi

[ $? -eq 0 ] && _success "Cancion descargada" || _error "Error al descargar"
