#!/usr/bin/env bash
##? help  : Download video playlist.
##? usage : yt-video-list [url]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

yt-dlp -w \
	--embed-metadata \
	--quiet --progress \
	-f mp4 \
	-o "$(xdg-user-dir DOWNLOAD)/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" $@

if [ $? -eq 0 ]; then
	_success "Videos descargado"
else
	_error "Error al descargar"
fi
