#!/usr/bin/env bash
##? usage : yt-video-file [file]
##? help  : Download all video from url save in file.

yt-dlp --no-playlist \
	--embed-metadata \
	-f mp4 \
	-o "$(xdg-user-dir DOWNLOAD)/%(title)s.%(ext)s" \
	--batch-file $@
