#!/usr/bin/env bash
##? Help : Download all video from url save in file.
##? Usage: yt-video-file <file>

yt-dlp --no-playlist \
	--embed-metadata \
	-f mp4 \
	-o "$(xdg-user-dir DOWNLOAD)/%(title)s.%(ext)s" \
	--batch-file $@
