#!/usr/bin/env bash
##? help  : Download video.
##? usage : yt-video [url|file]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

if [[ $1 =~ $playlist_regex ]]; then
	yt-dlp -w \
		--embed-metadata \
		--quiet --progress \
		-f "bv*+ba/b" -S "res:1080,ext:mp4:m4a" \
		-o "$(xdg-user-dir DOWNLOAD)/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" $@
elif [[ $1 =~ $video_regex ]]; then
	yt-dlp --no-playlist --embed-metadata \
		--quiet --progress \
		-f "bv*+ba/b" -S "res:1080,ext:mp4:m4a" \
		-o "$(xdg-user-dir DOWNLOAD)/%(title)s.%(ext)s" $@
elif [ -f "$1" ]; then
	yt-dlp --no-playlist \
		--embed-metadata \
		--quiet --progress \
		-f "bv*+ba/b" -S "res:1080,ext:mp4:m4a" \
		-o "$(xdg-user-dir DOWNLOAD)/%(title)s.%(ext)s" \
		--batch-file $@
fi

if [ $? -eq 0 ]; then
	_success "Video descargado"
else
	_error "Error al descargar"
fi
