#!/usr/bin/env bash
##? help  : Download video.
##? usage : yt-video [url]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

yt-dlp --no-playlist --embed-metadata \
	--quiet --progress \
	-f mp4 \
	-o "$(xdg-user-dir DOWNLOAD)/%(title)s.%(ext)s" $@

if [ $? -eq 0 ]; then
	_success "Video descargado"
else
	_error "Error al descargar"
fi
