#!/usr/bin/env sh
# ? description: List all jpg in subfolders and rename by counter: (001,002...).
# ? usage      : image_sequential [none]

counter=0

fd -tf . -e jpg -e jpeg -e png -e gif | sort -fV | while read -r file; do
    ext="${file##*.}"
    mv -v "$file" "$(printf "%03d" $counter).$ext"
    ((counter++))
done
