#!/usr/bin/env sh
# ? description: Transform images into pdf.
# ? usage      : image_pdfs [folder(s)]

. "$HOME/.bin/_main.sh"

[ $# -lt 1 ] && _params_required 1 && exit 1

base_dir="$1"

# Procesar imágenes en el directorio base
if ls "$base_dir"/*.jpg 1> /dev/null 2>&1; then
    echo "Procesando imágenes en '$(basename "$base_dir")'..."
    mogrify -strip "$base_dir"/*.jpg
    img2pdf -o "$(basename "$base_dir").pdf" "$base_dir"/*.jpg
fi

# Procesar imágenes en subdirectorios
for folder in "$base_dir"/*/; do
    [[ -d "$folder" ]] || continue

    if ls "$folder"/*.jpg 1> /dev/null 2>&1; then
        echo "Procesando imágenes en '$(basename "$folder")'..."
        mogrify -strip "$folder"/*.jpg
        img2pdf -o "$(basename "$folder").pdf" "$folder"/*.jpg
    else
        echo "No se encontraron imágenes JPG en '$(basename "$folder")'."
    fi
done
