#!/usr/bin/env bash
##? help  : Transform text into qr image.
##? usage : qr [text] [output-name]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 2 ]]; then
	_params_required 2
	exit 1
fi

texto="$1"
archivo_salida="$2.png"

# URL de la API
url="https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=$texto"

# Descargar el código QR y guardarlo en un archivo
curl -o "$archivo_salida" "$url"

_LOG "Código QR generado con éxito en: $archivo_salida"
