#!/usr/bin/env bash
##? help  : Convert image to png format.
##? usage : to_png [file...]

source "$HOME/.bin/_main.sh"

if [[ $# -lt 1 ]]; then
	_params_required 1
	exit 1
fi

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	convert "$f" -background white "$folder/$name.png" >/dev/null 2>&1
	if [ $? -eq 0 ]; then
		_success "Convertido: $f -> $name.png"
	else
		_error "Error al convertir: $f"
	fi
done
